main: com.tenjava.slipcor.BowsPlus
name: BowsPlus
description: BowsPlus
author: slipcor
version: 0.0.5.1
commands:
  bowsplus:
    aliases: ['bp']
    description: add stuff to your bow
    usage: /<command> [TYPE] {subvalue1} {subvalue2}
  bowsplusreload:
    aliases: ['bpr']
    description: reload the command
    usage: /<command>
    permission: bowsplus.admin
permissions:
  bowsplus.admin:
    description: allow to admin the plugin
    default: op
    permission-message: you do not have the permission <permission> 